//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionConstant.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="actionConstant">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Activation"/>
 *     <enumeration value="Update"/>
 *     <enumeration value="Deactivation"/>
 *     <enumeration value="Query"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "actionConstant")
@XmlEnum
public enum ActionConstant {

    @XmlEnumValue("Activation")
    ACTIVATION("Activation"),
    @XmlEnumValue("Update")
    UPDATE("Update"),
    @XmlEnumValue("Deactivation")
    DEACTIVATION("Deactivation"),
    @XmlEnumValue("Query")
    QUERY("Query");
    private final String value;

    ActionConstant(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionConstant fromValue(String v) {
        for (ActionConstant c: ActionConstant.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
