//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionConstant.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="actionConstant"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Activation"/&gt;
 *     &lt;enumeration value="Update"/&gt;
 *     &lt;enumeration value="Deactivation"/&gt;
 *     &lt;enumeration value="Query"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "actionConstant")
@XmlEnum
public enum ActionConstant {

    @XmlEnumValue("Activation")
    ACTIVATION("Activation"),
    @XmlEnumValue("Update")
    UPDATE("Update"),
    @XmlEnumValue("Deactivation")
    DEACTIVATION("Deactivation"),
    @XmlEnumValue("Query")
    QUERY("Query");
    private final String value;

    ActionConstant(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionConstant fromValue(String v) {
        for (ActionConstant c: ActionConstant.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
