//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for adjFlagType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="adjFlagType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RRC"/&gt;
 *     &lt;enumeration value="RET"/&gt;
 *     &lt;enumeration value="PBRB"/&gt;
 *     &lt;enumeration value="TCC"/&gt;
 *     &lt;enumeration value="DRC"/&gt;
 *     &lt;enumeration value="NAC"/&gt;
 *     &lt;enumeration value="REF"/&gt;
 *     &lt;enumeration value="BTO"/&gt;
 *     &lt;enumeration value="PTO"/&gt;
 *     &lt;enumeration value="BUU"/&gt;
 *     &lt;enumeration value="PUU"/&gt;
 *     &lt;enumeration value="RUU"/&gt;
 *     &lt;enumeration value="PR2C"/&gt;
 *     &lt;enumeration value="UTO"/&gt;
 *     &lt;enumeration value="B"/&gt;
 *     &lt;enumeration value="A"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "adjFlagType")
@XmlEnum
public enum AdjFlagType {

    RRC("RRC"),
    RET("RET"),
    PBRB("PBRB"),
    TCC("TCC"),
    DRC("DRC"),
    NAC("NAC"),
    REF("REF"),
    BTO("BTO"),
    PTO("PTO"),
    BUU("BUU"),
    PUU("PUU"),
    RUU("RUU"),
    @XmlEnumValue("PR2C")
    PR_2_C("PR2C"),
    UTO("UTO"),
    B("B"),
    A("A");
    private final String value;

    AdjFlagType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AdjFlagType fromValue(String v) {
        for (AdjFlagType c: AdjFlagType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
