//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for channelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="channelType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="BRANCH"/>
 *     <enumeration value="MOBILE"/>
 *     <enumeration value="INB"/>
 *     <enumeration value="CHQ"/>
 *     <enumeration value="ATM"/>
 *     <enumeration value="IVR"/>
 *     <enumeration value="MOB"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "channelType")
@XmlEnum
public enum ChannelType {

    BRANCH,
    MOBILE,
    INB,
    CHQ,
    ATM,
    IVR,
    MOB;

    public String value() {
        return name();
    }

    public static ChannelType fromValue(String v) {
        return valueOf(v);
    }

}
