//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complaintType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complaintType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Creds" type="{http://npci.org/upi/schema/}credsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="reqAdjFlag" type="{http://npci.org/upi/schema/}adjFlagType" /&gt;
 *       &lt;attribute name="reqAdjCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="reqAdjAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="orgSettRespCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="currCycle" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complaintType", propOrder = {
    "creds"
})
public class ComplaintType {

    @XmlElement(name = "Creds")
    protected CredsType creds;
    @XmlAttribute(name = "reqAdjFlag")
    protected AdjFlagType reqAdjFlag;
    @XmlAttribute(name = "reqAdjCode")
    protected String reqAdjCode;
    @XmlAttribute(name = "reqAdjAmount")
    protected String reqAdjAmount;
    @XmlAttribute(name = "orgSettRespCode")
    protected String orgSettRespCode;
    @XmlAttribute(name = "currCycle")
    protected String currCycle;

    /**
     * Gets the value of the creds property.
     * 
     * @return
     *     possible object is
     *     {@link CredsType }
     *     
     */
    public CredsType getCreds() {
        return creds;
    }

    /**
     * Sets the value of the creds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredsType }
     *     
     */
    public void setCreds(CredsType value) {
        this.creds = value;
    }

    /**
     * Gets the value of the reqAdjFlag property.
     * 
     * @return
     *     possible object is
     *     {@link AdjFlagType }
     *     
     */
    public AdjFlagType getReqAdjFlag() {
        return reqAdjFlag;
    }

    /**
     * Sets the value of the reqAdjFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjFlagType }
     *     
     */
    public void setReqAdjFlag(AdjFlagType value) {
        this.reqAdjFlag = value;
    }

    /**
     * Gets the value of the reqAdjCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqAdjCode() {
        return reqAdjCode;
    }

    /**
     * Sets the value of the reqAdjCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqAdjCode(String value) {
        this.reqAdjCode = value;
    }

    /**
     * Gets the value of the reqAdjAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqAdjAmount() {
        return reqAdjAmount;
    }

    /**
     * Sets the value of the reqAdjAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqAdjAmount(String value) {
        this.reqAdjAmount = value;
    }

    /**
     * Gets the value of the orgSettRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgSettRespCode() {
        return orgSettRespCode;
    }

    /**
     * Sets the value of the orgSettRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgSettRespCode(String value) {
        this.orgSettRespCode = value;
    }

    /**
     * Gets the value of the currCycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrCycle() {
        return currCycle;
    }

    /**
     * Sets the value of the currCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrCycle(String value) {
        this.currCycle = value;
    }

}
