//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consentTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="consentTypeEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="PAN"/>
 *     <enumeration value="AADHAAR"/>
 *     <enumeration value="AADHAARTOKEN "/>
 *     <enumeration value="PASSPORT"/>
 *     <enumeration value="VOTERID"/>
 *     <enumeration value="DRIVINGLICENSE"/>
 *     <enumeration value="GSTIN"/>
 *     <enumeration value="NUMERICID"/>
 *     <enumeration value="MOBILE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "consentTypeEnum")
@XmlEnum
public enum ConsentTypeEnum {

    PAN("PAN"),
    AADHAAR("AADHAAR"),
    @XmlEnumValue("AADHAARTOKEN ")
    AADHAARTOKEN("AADHAARTOKEN "),
    PASSPORT("PASSPORT"),
    VOTERID("VOTERID"),
    DRIVINGLICENSE("DRIVINGLICENSE"),
    GSTIN("GSTIN"),
    NUMERICID("NUMERICID"),
    MOBILE("MOBILE");
    private final String value;

    ConsentTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConsentTypeEnum fromValue(String v) {
        for (ConsentTypeEnum c: ConsentTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
