//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consentTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="consentTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PAN"/&gt;
 *     &lt;enumeration value="AADHAAR"/&gt;
 *     &lt;enumeration value="AADHAARTOKEN "/&gt;
 *     &lt;enumeration value="PASSPORT"/&gt;
 *     &lt;enumeration value="VOTERID"/&gt;
 *     &lt;enumeration value="DRIVINGLICENSE"/&gt;
 *     &lt;enumeration value="GSTIN"/&gt;
 *     &lt;enumeration value="NUMERICID"/&gt;
 *     &lt;enumeration value="MOBILE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "consentTypeEnum")
@XmlEnum
public enum ConsentTypeEnum {

    PAN("PAN"),
    AADHAAR("AADHAAR"),
    @XmlEnumValue("AADHAARTOKEN ")
    AADHAARTOKEN("AADHAARTOKEN "),
    PASSPORT("PASSPORT"),
    VOTERID("VOTERID"),
    DRIVINGLICENSE("DRIVINGLICENSE"),
    GSTIN("GSTIN"),
    NUMERICID("NUMERICID"),
    MOBILE("MOBILE");
    private final String value;

    ConsentTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConsentTypeEnum fromValue(String v) {
        for (ConsentTypeEnum c: ConsentTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
