//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for credType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="credType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="AADHAAR"/>
 *     <enumeration value="OTP"/>
 *     <enumeration value="PIN"/>
 *     <enumeration value="CARD"/>
 *     <enumeration value="PreApproved"/>
 *     <enumeration value="Challenge"/>
 *     <enumeration value="UPI-Mandate"/>
 *     <enumeration value="PostCredit"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "credType")
@XmlEnum
public enum CredType {

    AADHAAR("AADHAAR"),
    OTP("OTP"),
    PIN("PIN"),
    CARD("CARD"),
    @XmlEnumValue("PreApproved")
    PRE_APPROVED("PreApproved"),
    @XmlEnumValue("Challenge")
    CHALLENGE("Challenge"),
    @XmlEnumValue("UPI-Mandate")
    UPI_MANDATE("UPI-Mandate"),
    @XmlEnumValue("PostCredit")
    POST_CREDIT("PostCredit");
    private final String value;

    CredType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CredType fromValue(String v) {
        for (CredType c: CredType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
