//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for credsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="credsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Cred" maxOccurs="10">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Data">
 *                     <complexType>
 *                       <simpleContent>
 *                         <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                           <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           <attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         </extension>
 *                       </simpleContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="Auth" type="{http://npci.org/upi/schema/}Auth" minOccurs="0"/>
 *                   <element name="Otp" type="{http://npci.org/upi/schema/}Otp" minOccurs="0"/>
 *                   <element name="KycReqInfo" type="{http://npci.org/upi/schema/}KycReqInfo" minOccurs="0"/>
 *                   <element name="Meta" type="{http://npci.org/upi/schema/}MetaType" minOccurs="0"/>
 *                 </sequence>
 *                 <attribute name="type" use="required" type="{http://npci.org/upi/schema/}credType" />
 *                 <attribute name="subType" use="required" type="{http://npci.org/upi/schema/}credSubType" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "credsType", propOrder = {
    "cred"
})
public class CredsType {

    @XmlElement(name = "Cred", required = true)
    protected List<CredsType.Cred> cred;

    /**
     * Gets the value of the cred property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the cred property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCred().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CredsType.Cred }
     * 
     * 
     * @return
     *     The value of the cred property.
     */
    public List<CredsType.Cred> getCred() {
        if (cred == null) {
            cred = new ArrayList<>();
        }
        return this.cred;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Data">
     *           <complexType>
     *             <simpleContent>
     *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *                 <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 <attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               </extension>
     *             </simpleContent>
     *           </complexType>
     *         </element>
     *         <element name="Auth" type="{http://npci.org/upi/schema/}Auth" minOccurs="0"/>
     *         <element name="Otp" type="{http://npci.org/upi/schema/}Otp" minOccurs="0"/>
     *         <element name="KycReqInfo" type="{http://npci.org/upi/schema/}KycReqInfo" minOccurs="0"/>
     *         <element name="Meta" type="{http://npci.org/upi/schema/}MetaType" minOccurs="0"/>
     *       </sequence>
     *       <attribute name="type" use="required" type="{http://npci.org/upi/schema/}credType" />
     *       <attribute name="subType" use="required" type="{http://npci.org/upi/schema/}credSubType" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "data",
        "auth",
        "otp",
        "kycReqInfo",
        "meta"
    })
    public static class Cred {

        @XmlElement(name = "Data", required = true)
        protected CredsType.Cred.Data data;
        @XmlElement(name = "Auth")
        protected Auth auth;
        @XmlElement(name = "Otp")
        protected Otp otp;
        @XmlElement(name = "KycReqInfo")
        protected KycReqInfo kycReqInfo;
        @XmlElement(name = "Meta")
        protected MetaType meta;
        @XmlAttribute(name = "type", required = true)
        protected CredType type;
        @XmlAttribute(name = "subType", required = true)
        protected CredSubType subType;

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link CredsType.Cred.Data }
         *     
         */
        public CredsType.Cred.Data getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link CredsType.Cred.Data }
         *     
         */
        public void setData(CredsType.Cred.Data value) {
            this.data = value;
        }

        /**
         * Gets the value of the auth property.
         * 
         * @return
         *     possible object is
         *     {@link Auth }
         *     
         */
        public Auth getAuth() {
            return auth;
        }

        /**
         * Sets the value of the auth property.
         * 
         * @param value
         *     allowed object is
         *     {@link Auth }
         *     
         */
        public void setAuth(Auth value) {
            this.auth = value;
        }

        /**
         * Gets the value of the otp property.
         * 
         * @return
         *     possible object is
         *     {@link Otp }
         *     
         */
        public Otp getOtp() {
            return otp;
        }

        /**
         * Sets the value of the otp property.
         * 
         * @param value
         *     allowed object is
         *     {@link Otp }
         *     
         */
        public void setOtp(Otp value) {
            this.otp = value;
        }

        /**
         * Gets the value of the kycReqInfo property.
         * 
         * @return
         *     possible object is
         *     {@link KycReqInfo }
         *     
         */
        public KycReqInfo getKycReqInfo() {
            return kycReqInfo;
        }

        /**
         * Sets the value of the kycReqInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link KycReqInfo }
         *     
         */
        public void setKycReqInfo(KycReqInfo value) {
            this.kycReqInfo = value;
        }

        /**
         * Gets the value of the meta property.
         * 
         * @return
         *     possible object is
         *     {@link MetaType }
         *     
         */
        public MetaType getMeta() {
            return meta;
        }

        /**
         * Sets the value of the meta property.
         * 
         * @param value
         *     allowed object is
         *     {@link MetaType }
         *     
         */
        public void setMeta(MetaType value) {
            this.meta = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link CredType }
         *     
         */
        public CredType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link CredType }
         *     
         */
        public void setType(CredType value) {
            this.type = value;
        }

        /**
         * Gets the value of the subType property.
         * 
         * @return
         *     possible object is
         *     {@link CredSubType }
         *     
         */
        public CredSubType getSubType() {
            return subType;
        }

        /**
         * Sets the value of the subType property.
         * 
         * @param value
         *     allowed object is
         *     {@link CredSubType }
         *     
         */
        public void setSubType(CredSubType value) {
            this.subType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <simpleContent>
         *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
         *       <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       <attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     </extension>
         *   </simpleContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Data {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "code")
            protected String code;
            @XmlAttribute(name = "ki")
            protected String ki;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the ki property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKi() {
                return ki;
            }

            /**
             * Sets the value of the ki property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKi(String value) {
                this.ki = value;
            }

        }

    }

}
