//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for credDataTypeConstant.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="credDataTypeConstant">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Alphanumeric"/>
 *     <enumeration value="Numeric"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "credDataTypeConstant")
@XmlEnum
public enum CredDataTypeConstant {

    @XmlEnumValue("Alphanumeric")
    ALPHANUMERIC("Alphanumeric"),
    @XmlEnumValue("Numeric")
    NUMERIC("Numeric");
    private final String value;

    CredDataTypeConstant(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CredDataTypeConstant fromValue(String v) {
        for (CredDataTypeConstant c: CredDataTypeConstant.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
