//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for credSubType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="credSubType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="IIR"/>
 *     <enumeration value="FMR"/>
 *     <enumeration value="FIR"/>
 *     <enumeration value="OTP"/>
 *     <enumeration value="SMS"/>
 *     <enumeration value="EMAIL"/>
 *     <enumeration value="HOTP"/>
 *     <enumeration value="TOTP"/>
 *     <enumeration value="MPIN"/>
 *     <enumeration value="ATMPIN"/>
 *     <enumeration value="CVV1"/>
 *     <enumeration value="CVV2"/>
 *     <enumeration value="EMV"/>
 *     <enumeration value="initial"/>
 *     <enumeration value="reset"/>
 *     <enumeration value="rotate"/>
 *     <enumeration value="NA"/>
 *     <enumeration value="AADHAAR-BIO-FP"/>
 *     <enumeration value="AADHAAR-BIO-IRIS"/>
 *     <enumeration value="AADHAAR-BIO-OTP"/>
 *     <enumeration value="DS"/>
 *     <enumeration value="CARDDETAILS"/>
 *     <enumeration value="FACEAUTH"/>
 *     <enumeration value="UIDAI-AUTH-CODE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "credSubType")
@XmlEnum
public enum CredSubType {

    IIR("IIR"),
    FMR("FMR"),
    FIR("FIR"),
    OTP("OTP"),
    SMS("SMS"),
    EMAIL("EMAIL"),
    HOTP("HOTP"),
    TOTP("TOTP"),
    MPIN("MPIN"),
    ATMPIN("ATMPIN"),
    @XmlEnumValue("CVV1")
    CVV_1("CVV1"),
    @XmlEnumValue("CVV2")
    CVV_2("CVV2"),
    EMV("EMV"),
    @XmlEnumValue("initial")
    INITIAL("initial"),
    @XmlEnumValue("reset")
    RESET("reset"),
    @XmlEnumValue("rotate")
    ROTATE("rotate"),
    NA("NA"),
    @XmlEnumValue("AADHAAR-BIO-FP")
    AADHAAR_BIO_FP("AADHAAR-BIO-FP"),
    @XmlEnumValue("AADHAAR-BIO-IRIS")
    AADHAAR_BIO_IRIS("AADHAAR-BIO-IRIS"),
    @XmlEnumValue("AADHAAR-BIO-OTP")
    AADHAAR_BIO_OTP("AADHAAR-BIO-OTP"),
    DS("DS"),
    CARDDETAILS("CARDDETAILS"),
    FACEAUTH("FACEAUTH"),
    @XmlEnumValue("UIDAI-AUTH-CODE")
    UIDAI_AUTH_CODE("UIDAI-AUTH-CODE");
    private final String value;

    CredSubType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CredSubType fromValue(String v) {
        for (CredSubType c: CredSubType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
