//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CurrValType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CurrValType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="baseCurr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="uniQuotesId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="valEndTs" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fxRate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="markup" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="contraAmt" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="txnAmt" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="valueDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrValType")
public class CurrValType {

    @XmlAttribute(name = "baseCurr")
    protected String baseCurr;
    @XmlAttribute(name = "uniQuotesId")
    protected String uniQuotesId;
    @XmlAttribute(name = "valEndTs")
    protected String valEndTs;
    @XmlAttribute(name = "fxRate")
    protected String fxRate;
    @XmlAttribute(name = "markup")
    protected String markup;
    @XmlAttribute(name = "contraAmt")
    protected String contraAmt;
    @XmlAttribute(name = "txnAmt")
    protected String txnAmt;
    @XmlAttribute(name = "valueDate")
    protected String valueDate;

    /**
     * Gets the value of the baseCurr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCurr() {
        return baseCurr;
    }

    /**
     * Sets the value of the baseCurr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCurr(String value) {
        this.baseCurr = value;
    }

    /**
     * Gets the value of the uniQuotesId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniQuotesId() {
        return uniQuotesId;
    }

    /**
     * Sets the value of the uniQuotesId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniQuotesId(String value) {
        this.uniQuotesId = value;
    }

    /**
     * Gets the value of the valEndTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValEndTs() {
        return valEndTs;
    }

    /**
     * Sets the value of the valEndTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValEndTs(String value) {
        this.valEndTs = value;
    }

    /**
     * Gets the value of the fxRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFxRate() {
        return fxRate;
    }

    /**
     * Sets the value of the fxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFxRate(String value) {
        this.fxRate = value;
    }

    /**
     * Gets the value of the markup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkup() {
        return markup;
    }

    /**
     * Sets the value of the markup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkup(String value) {
        this.markup = value;
    }

    /**
     * Gets the value of the contraAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContraAmt() {
        return contraAmt;
    }

    /**
     * Sets the value of the contraAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContraAmt(String value) {
        this.contraAmt = value;
    }

    /**
     * Gets the value of the txnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnAmt() {
        return txnAmt;
    }

    /**
     * Sets the value of the txnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnAmt(String value) {
        this.txnAmt = value;
    }

    /**
     * Gets the value of the valueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDate() {
        return valueDate;
    }

    /**
     * Sets the value of the valueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDate(String value) {
        this.valueDate = value;
    }

}
