//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dealtTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="dealtTypeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="SPOT"/>
 *     <enumeration value="FORWARD"/>
 *     <enumeration value="NDF"/>
 *     <enumeration value="SWAPS"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "dealtTypeType")
@XmlEnum
public enum DealtTypeType {

    SPOT,
    FORWARD,
    NDF,
    SWAPS;

    public String value() {
        return name();
    }

    public static DealtTypeType fromValue(String v) {
        return valueOf(v);
    }

}
