//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deviceTagNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="deviceTagNameType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="MOBILE"/>
 *     <enumeration value="GEOCODE"/>
 *     <enumeration value="LOCATION"/>
 *     <enumeration value="IP"/>
 *     <enumeration value="TYPE"/>
 *     <enumeration value="ID"/>
 *     <enumeration value="OS"/>
 *     <enumeration value="APP"/>
 *     <enumeration value="CAPABILITY"/>
 *     <enumeration value="TELECOM"/>
 *     <enumeration value="cardAccpTrId"/>
 *     <enumeration value="cardAccIdCode"/>
 *     <enumeration value="posEntryCode"/>
 *     <enumeration value="posServCdnCode"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "deviceTagNameType")
@XmlEnum
public enum DeviceTagNameType {

    MOBILE("MOBILE"),
    GEOCODE("GEOCODE"),
    LOCATION("LOCATION"),
    IP("IP"),
    TYPE("TYPE"),
    ID("ID"),
    OS("OS"),
    APP("APP"),
    CAPABILITY("CAPABILITY"),
    TELECOM("TELECOM"),
    @XmlEnumValue("cardAccpTrId")
    CARD_ACCP_TR_ID("cardAccpTrId"),
    @XmlEnumValue("cardAccIdCode")
    CARD_ACC_ID_CODE("cardAccIdCode"),
    @XmlEnumValue("posEntryCode")
    POS_ENTRY_CODE("posEntryCode"),
    @XmlEnumValue("posServCdnCode")
    POS_SERV_CDN_CODE("posServCdnCode");
    private final String value;

    DeviceTagNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeviceTagNameType fromValue(String v) {
        for (DeviceTagNameType c: DeviceTagNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
