//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fxListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fxListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Fx" maxOccurs="10" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="baseAmount" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="baseCurr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="active" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="Fx" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="Mkup" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="lastModifedTs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fxListType", propOrder = {
    "fx"
})
public class FxListType {

    @XmlElement(name = "Fx")
    protected List<FxListType.Fx> fx;

    /**
     * Gets the value of the fx property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the fx property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFx().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FxListType.Fx }
     * 
     * 
     */
    public List<FxListType.Fx> getFx() {
        if (fx == null) {
            fx = new ArrayList<FxListType.Fx>();
        }
        return this.fx;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="baseAmount" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="baseCurr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="active" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="Fx" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="Mkup" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="lastModifedTs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Fx {

        @XmlAttribute(name = "baseAmount", required = true)
        protected String baseAmount;
        @XmlAttribute(name = "baseCurr", required = true)
        protected String baseCurr;
        @XmlAttribute(name = "active", required = true)
        protected String active;
        @XmlAttribute(name = "Fx", required = true)
        protected String fx;
        @XmlAttribute(name = "Mkup", required = true)
        protected String mkup;
        @XmlAttribute(name = "lastModifedTs", required = true)
        protected String lastModifedTs;

        /**
         * Gets the value of the baseAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBaseAmount() {
            return baseAmount;
        }

        /**
         * Sets the value of the baseAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBaseAmount(String value) {
            this.baseAmount = value;
        }

        /**
         * Gets the value of the baseCurr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBaseCurr() {
            return baseCurr;
        }

        /**
         * Sets the value of the baseCurr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBaseCurr(String value) {
            this.baseCurr = value;
        }

        /**
         * Gets the value of the active property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActive() {
            return active;
        }

        /**
         * Sets the value of the active property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActive(String value) {
            this.active = value;
        }

        /**
         * Gets the value of the fx property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFx() {
            return fx;
        }

        /**
         * Sets the value of the fx property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFx(String value) {
            this.fx = value;
        }

        /**
         * Gets the value of the mkup property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMkup() {
            return mkup;
        }

        /**
         * Sets the value of the mkup property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMkup(String value) {
            this.mkup = value;
        }

        /**
         * Gets the value of the lastModifedTs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastModifedTs() {
            return lastModifedTs;
        }

        /**
         * Sets the value of the lastModifedTs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastModifedTs(String value) {
            this.lastModifedTs = value;
        }

    }

}
