//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for idDetailType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="idDetailType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACNUM"/&gt;
 *     &lt;enumeration value="MASKNAME"/&gt;
 *     &lt;enumeration value="IFSC"/&gt;
 *     &lt;enumeration value="ACTYPE"/&gt;
 *     &lt;enumeration value="ACNATURE"/&gt;
 *     &lt;enumeration value="ACHOLDER"/&gt;
 *     &lt;enumeration value="CODE"/&gt;
 *     &lt;enumeration value="TYPE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "idDetailType")
@XmlEnum
public enum IdDetailType {

    ACNUM,
    MASKNAME,
    IFSC,
    ACTYPE,
    ACNATURE,
    ACHOLDER,
    CODE,
    TYPE;

    public String value() {
        return name();
    }

    public static IdDetailType fromValue(String v) {
        return valueOf(v);
    }

}
