//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for institutionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="institutionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://npci.org/upi/schema/}institutionName"/&gt;
 *         &lt;element name="Purpose" type="{http://npci.org/upi/schema/}institutionPurpose"/&gt;
 *         &lt;element name="Originator" type="{http://npci.org/upi/schema/}institutionOriginator"/&gt;
 *         &lt;element name="Beneficiary" type="{http://npci.org/upi/schema/}institutionBeneficiary"/&gt;
 *         &lt;element name="CurrVal" type="{http://npci.org/upi/schema/}CurrValType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" use="required" type="{http://npci.org/upi/schema/}institutionAttrType" /&gt;
 *       &lt;attribute name="route" use="required" type="{http://npci.org/upi/schema/}institutionRoute" /&gt;
 *       &lt;attribute name="netInstId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="QrPayLoad" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="conCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="baseCurr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tenor" type="{http://npci.org/upi/schema/}tenorConstants" /&gt;
 *       &lt;attribute name="validity" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "institutionType", propOrder = {
    "name",
    "purpose",
    "originator",
    "beneficiary",
    "currVal"
})
public class InstitutionType {

    @XmlElement(name = "Name", required = true)
    protected InstitutionName name;
    @XmlElement(name = "Purpose", required = true)
    protected InstitutionPurpose purpose;
    @XmlElement(name = "Originator", required = true)
    protected InstitutionOriginator originator;
    @XmlElement(name = "Beneficiary", required = true)
    protected InstitutionBeneficiary beneficiary;
    @XmlElement(name = "CurrVal", required = true)
    protected CurrValType currVal;
    @XmlAttribute(name = "type", required = true)
    protected InstitutionAttrType type;
    @XmlAttribute(name = "route", required = true)
    protected InstitutionRoute route;
    @XmlAttribute(name = "netInstId")
    protected String netInstId;
    @XmlAttribute(name = "QrPayLoad")
    protected String qrPayLoad;
    @XmlAttribute(name = "conCode")
    protected String conCode;
    @XmlAttribute(name = "baseCurr")
    protected String baseCurr;
    @XmlAttribute(name = "tenor")
    protected TenorConstants tenor;
    @XmlAttribute(name = "validity")
    protected String validity;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionName }
     *     
     */
    public InstitutionName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionName }
     *     
     */
    public void setName(InstitutionName value) {
        this.name = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionPurpose }
     *     
     */
    public InstitutionPurpose getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionPurpose }
     *     
     */
    public void setPurpose(InstitutionPurpose value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the originator property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionOriginator }
     *     
     */
    public InstitutionOriginator getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionOriginator }
     *     
     */
    public void setOriginator(InstitutionOriginator value) {
        this.originator = value;
    }

    /**
     * Gets the value of the beneficiary property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionBeneficiary }
     *     
     */
    public InstitutionBeneficiary getBeneficiary() {
        return beneficiary;
    }

    /**
     * Sets the value of the beneficiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionBeneficiary }
     *     
     */
    public void setBeneficiary(InstitutionBeneficiary value) {
        this.beneficiary = value;
    }

    /**
     * Gets the value of the currVal property.
     * 
     * @return
     *     possible object is
     *     {@link CurrValType }
     *     
     */
    public CurrValType getCurrVal() {
        return currVal;
    }

    /**
     * Sets the value of the currVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrValType }
     *     
     */
    public void setCurrVal(CurrValType value) {
        this.currVal = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionAttrType }
     *     
     */
    public InstitutionAttrType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionAttrType }
     *     
     */
    public void setType(InstitutionAttrType value) {
        this.type = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionRoute }
     *     
     */
    public InstitutionRoute getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionRoute }
     *     
     */
    public void setRoute(InstitutionRoute value) {
        this.route = value;
    }

    /**
     * Gets the value of the netInstId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetInstId() {
        return netInstId;
    }

    /**
     * Sets the value of the netInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetInstId(String value) {
        this.netInstId = value;
    }

    /**
     * Gets the value of the qrPayLoad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrPayLoad() {
        return qrPayLoad;
    }

    /**
     * Sets the value of the qrPayLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrPayLoad(String value) {
        this.qrPayLoad = value;
    }

    /**
     * Gets the value of the conCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConCode() {
        return conCode;
    }

    /**
     * Sets the value of the conCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConCode(String value) {
        this.conCode = value;
    }

    /**
     * Gets the value of the baseCurr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCurr() {
        return baseCurr;
    }

    /**
     * Sets the value of the baseCurr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCurr(String value) {
        this.baseCurr = value;
    }

    /**
     * Gets the value of the tenor property.
     * 
     * @return
     *     possible object is
     *     {@link TenorConstants }
     *     
     */
    public TenorConstants getTenor() {
        return tenor;
    }

    /**
     * Sets the value of the tenor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TenorConstants }
     *     
     */
    public void setTenor(TenorConstants value) {
        this.tenor = value;
    }

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidity(String value) {
        this.validity = value;
    }

}
