//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KycReqInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="KycReqInfo">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="ra" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="rc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="lr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="de" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="pfr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KycReqInfo", propOrder = {
    "ver",
    "ra",
    "rc",
    "lr",
    "de",
    "pfr"
})
public class KycReqInfo {

    @XmlElement(required = true)
    protected String ver;
    @XmlElement(required = true)
    protected String ra;
    @XmlElement(required = true)
    protected String rc;
    @XmlElement(required = true)
    protected String lr;
    @XmlElement(required = true)
    protected String de;
    @XmlElement(required = true)
    protected String pfr;

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVer() {
        return ver;
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVer(String value) {
        this.ver = value;
    }

    /**
     * Gets the value of the ra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRa() {
        return ra;
    }

    /**
     * Sets the value of the ra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRa(String value) {
        this.ra = value;
    }

    /**
     * Gets the value of the rc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRc() {
        return rc;
    }

    /**
     * Sets the value of the rc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRc(String value) {
        this.rc = value;
    }

    /**
     * Gets the value of the lr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLr() {
        return lr;
    }

    /**
     * Sets the value of the lr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLr(String value) {
        this.lr = value;
    }

    /**
     * Gets the value of the de property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDe() {
        return de;
    }

    /**
     * Sets the value of the de property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDe(String value) {
        this.de = value;
    }

    /**
     * Gets the value of the pfr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPfr() {
        return pfr;
    }

    /**
     * Sets the value of the pfr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPfr(String value) {
        this.pfr = value;
    }

}
