//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fss.aeps.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fss.aeps.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RespBalEnq }
     * 
     * @return
     *     the new instance of {@link RespBalEnq }
     */
    public RespBalEnq createRespBalEnq() {
        return new RespBalEnq();
    }

    /**
     * Create an instance of {@link RespChkTxn }
     * 
     * @return
     *     the new instance of {@link RespChkTxn }
     */
    public RespChkTxn createRespChkTxn() {
        return new RespChkTxn();
    }

    /**
     * Create an instance of {@link ReqOtp }
     * 
     * @return
     *     the new instance of {@link ReqOtp }
     */
    public ReqOtp createReqOtp() {
        return new ReqOtp();
    }

    /**
     * Create an instance of {@link ReqPay }
     * 
     * @return
     *     the new instance of {@link ReqPay }
     */
    public ReqPay createReqPay() {
        return new ReqPay();
    }

    /**
     * Create an instance of {@link RespPay }
     * 
     * @return
     *     the new instance of {@link RespPay }
     */
    public RespPay createRespPay() {
        return new RespPay();
    }

    /**
     * Create an instance of {@link SHGInfo }
     * 
     * @return
     *     the new instance of {@link SHGInfo }
     */
    public SHGInfo createSHGInfo() {
        return new SHGInfo();
    }

    /**
     * Create an instance of {@link MetaListType }
     * 
     * @return
     *     the new instance of {@link MetaListType }
     */
    public MetaListType createMetaListType() {
        return new MetaListType();
    }

    /**
     * Create an instance of {@link FxListType }
     * 
     * @return
     *     the new instance of {@link FxListType }
     */
    public FxListType createFxListType() {
        return new FxListType();
    }

    /**
     * Create an instance of {@link MandateType }
     * 
     * @return
     *     the new instance of {@link MandateType }
     */
    public MandateType createMandateType() {
        return new MandateType();
    }

    /**
     * Create an instance of {@link RecurrenceType }
     * 
     * @return
     *     the new instance of {@link RecurrenceType }
     */
    public RecurrenceType createRecurrenceType() {
        return new RecurrenceType();
    }

    /**
     * Create an instance of {@link CredsType }
     * 
     * @return
     *     the new instance of {@link CredsType }
     */
    public CredsType createCredsType() {
        return new CredsType();
    }

    /**
     * Create an instance of {@link CredsType.Cred }
     * 
     * @return
     *     the new instance of {@link CredsType.Cred }
     */
    public CredsType.Cred createCredsTypeCred() {
        return new CredsType.Cred();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     * @return
     *     the new instance of {@link AccountType }
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link IdType }
     * 
     * @return
     *     the new instance of {@link IdType }
     */
    public IdType createIdType() {
        return new IdType();
    }

    /**
     * Create an instance of {@link ReqIdDetails }
     * 
     * @return
     *     the new instance of {@link ReqIdDetails }
     */
    public ReqIdDetails createReqIdDetails() {
        return new ReqIdDetails();
    }

    /**
     * Create an instance of {@link RegIdDetailsType }
     * 
     * @return
     *     the new instance of {@link RegIdDetailsType }
     */
    public RegIdDetailsType createRegIdDetailsType() {
        return new RegIdDetailsType();
    }

    /**
     * Create an instance of {@link DeviceType }
     * 
     * @return
     *     the new instance of {@link DeviceType }
     */
    public DeviceType createDeviceType() {
        return new DeviceType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     * @return
     *     the new instance of {@link AmountType }
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link RulesType }
     * 
     * @return
     *     the new instance of {@link RulesType }
     */
    public RulesType createRulesType() {
        return new RulesType();
    }

    /**
     * Create an instance of {@link RiskScoresType }
     * 
     * @return
     *     the new instance of {@link RiskScoresType }
     */
    public RiskScoresType createRiskScoresType() {
        return new RiskScoresType();
    }

    /**
     * Create an instance of {@link ReqPay.Meta }
     * 
     * @return
     *     the new instance of {@link ReqPay.Meta }
     */
    public ReqPay.Meta createReqPayMeta() {
        return new ReqPay.Meta();
    }

    /**
     * Create an instance of {@link ReqOtp.RegDetails }
     * 
     * @return
     *     the new instance of {@link ReqOtp.RegDetails }
     */
    public ReqOtp.RegDetails createReqOtpRegDetails() {
        return new ReqOtp.RegDetails();
    }

    /**
     * Create an instance of {@link RespBalEnq.Payer }
     * 
     * @return
     *     the new instance of {@link RespBalEnq.Payer }
     */
    public RespBalEnq.Payer createRespBalEnqPayer() {
        return new RespBalEnq.Payer();
    }

    /**
     * Create an instance of {@link RespBalEnq.Payer.MiniStatement }
     * 
     * @return
     *     the new instance of {@link RespBalEnq.Payer.MiniStatement }
     */
    public RespBalEnq.Payer.MiniStatement createRespBalEnqPayerMiniStatement() {
        return new RespBalEnq.Payer.MiniStatement();
    }

    /**
     * Create an instance of {@link RespBalEnq.Payer.Bal }
     * 
     * @return
     *     the new instance of {@link RespBalEnq.Payer.Bal }
     */
    public RespBalEnq.Payer.Bal createRespBalEnqPayerBal() {
        return new RespBalEnq.Payer.Bal();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     * @return
     *     the new instance of {@link HeadType }
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link Ack }
     * 
     * @return
     *     the new instance of {@link Ack }
     */
    public Ack createAck() {
        return new Ack();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     * @return
     *     the new instance of {@link ErrorMessage }
     */
    public ErrorMessage createErrorMessage() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link ReqBalEnq }
     * 
     * @return
     *     the new instance of {@link ReqBalEnq }
     */
    public ReqBalEnq createReqBalEnq() {
        return new ReqBalEnq();
    }

    /**
     * Create an instance of {@link PayTrans }
     * 
     * @return
     *     the new instance of {@link PayTrans }
     */
    public PayTrans createPayTrans() {
        return new PayTrans();
    }

    /**
     * Create an instance of {@link PayerType }
     * 
     * @return
     *     the new instance of {@link PayerType }
     */
    public PayerType createPayerType() {
        return new PayerType();
    }

    /**
     * Create an instance of {@link RespType }
     * 
     * @return
     *     the new instance of {@link RespType }
     */
    public RespType createRespType() {
        return new RespType();
    }

    /**
     * Create an instance of {@link ReqBioAuth }
     * 
     * @return
     *     the new instance of {@link ReqBioAuth }
     */
    public ReqBioAuth createReqBioAuth() {
        return new ReqBioAuth();
    }

    /**
     * Create an instance of {@link RespBioAuth }
     * 
     * @return
     *     the new instance of {@link RespBioAuth }
     */
    public RespBioAuth createRespBioAuth() {
        return new RespBioAuth();
    }

    /**
     * Create an instance of {@link UidaiData }
     * 
     * @return
     *     the new instance of {@link UidaiData }
     */
    public UidaiData createUidaiData() {
        return new UidaiData();
    }

    /**
     * Create an instance of {@link ReqChkTxn }
     * 
     * @return
     *     the new instance of {@link ReqChkTxn }
     */
    public ReqChkTxn createReqChkTxn() {
        return new ReqChkTxn();
    }

    /**
     * Create an instance of {@link PayeeType }
     * 
     * @return
     *     the new instance of {@link PayeeType }
     */
    public PayeeType createPayeeType() {
        return new PayeeType();
    }

    /**
     * Create an instance of {@link VerificationSequence }
     * 
     * @return
     *     the new instance of {@link VerificationSequence }
     */
    public VerificationSequence createVerificationSequence() {
        return new VerificationSequence();
    }

    /**
     * Create an instance of {@link RespChkTxn.Resp }
     * 
     * @return
     *     the new instance of {@link RespChkTxn.Resp }
     */
    public RespChkTxn.Resp createRespChkTxnResp() {
        return new RespChkTxn.Resp();
    }

    /**
     * Create an instance of {@link RespOtp }
     * 
     * @return
     *     the new instance of {@link RespOtp }
     */
    public RespOtp createRespOtp() {
        return new RespOtp();
    }

    /**
     * Create an instance of {@link ReqPanAuth }
     * 
     * @return
     *     the new instance of {@link ReqPanAuth }
     */
    public ReqPanAuth createReqPanAuth() {
        return new ReqPanAuth();
    }

    /**
     * Create an instance of {@link PayeesType }
     * 
     * @return
     *     the new instance of {@link PayeesType }
     */
    public PayeesType createPayeesType() {
        return new PayeesType();
    }

    /**
     * Create an instance of {@link ReInfoType }
     * 
     * @return
     *     the new instance of {@link ReInfoType }
     */
    public ReInfoType createReInfoType() {
        return new ReInfoType();
    }

    /**
     * Create an instance of {@link RespPanAuth }
     * 
     * @return
     *     the new instance of {@link RespPanAuth }
     */
    public RespPanAuth createRespPanAuth() {
        return new RespPanAuth();
    }

    /**
     * Create an instance of {@link ReqValAdd }
     * 
     * @return
     *     the new instance of {@link ReqValAdd }
     */
    public ReqValAdd createReqValAdd() {
        return new ReqValAdd();
    }

    /**
     * Create an instance of {@link RespValAdd }
     * 
     * @return
     *     the new instance of {@link RespValAdd }
     */
    public RespValAdd createRespValAdd() {
        return new RespValAdd();
    }

    /**
     * Create an instance of {@link RespTypeValAddr }
     * 
     * @return
     *     the new instance of {@link RespTypeValAddr }
     */
    public RespTypeValAddr createRespTypeValAddr() {
        return new RespTypeValAddr();
    }

    /**
     * Create an instance of {@link RespPay.Resp }
     * 
     * @return
     *     the new instance of {@link RespPay.Resp }
     */
    public RespPay.Resp createRespPayResp() {
        return new RespPay.Resp();
    }

    /**
     * Create an instance of {@link IdentityType }
     * 
     * @return
     *     the new instance of {@link IdentityType }
     */
    public IdentityType createIdentityType() {
        return new IdentityType();
    }

    /**
     * Create an instance of {@link TxnConfirmationType }
     * 
     * @return
     *     the new instance of {@link TxnConfirmationType }
     */
    public TxnConfirmationType createTxnConfirmationType() {
        return new TxnConfirmationType();
    }

    /**
     * Create an instance of {@link PayerInfoType }
     * 
     * @return
     *     the new instance of {@link PayerInfoType }
     */
    public PayerInfoType createPayerInfoType() {
        return new PayerInfoType();
    }

    /**
     * Create an instance of {@link RatingType }
     * 
     * @return
     *     the new instance of {@link RatingType }
     */
    public RatingType createRatingType() {
        return new RatingType();
    }

    /**
     * Create an instance of {@link RespTypeValCust }
     * 
     * @return
     *     the new instance of {@link RespTypeValCust }
     */
    public RespTypeValCust createRespTypeValCust() {
        return new RespTypeValCust();
    }

    /**
     * Create an instance of {@link RespIdDetails }
     * 
     * @return
     *     the new instance of {@link RespIdDetails }
     */
    public RespIdDetails createRespIdDetails() {
        return new RespIdDetails();
    }

    /**
     * Create an instance of {@link CredsAllowedType }
     * 
     * @return
     *     the new instance of {@link CredsAllowedType }
     */
    public CredsAllowedType createCredsAllowedType() {
        return new CredsAllowedType();
    }

    /**
     * Create an instance of {@link TxnConfDtl }
     * 
     * @return
     *     the new instance of {@link TxnConfDtl }
     */
    public TxnConfDtl createTxnConfDtl() {
        return new TxnConfDtl();
    }

    /**
     * Create an instance of {@link InfoType }
     * 
     * @return
     *     the new instance of {@link InfoType }
     */
    public InfoType createInfoType() {
        return new InfoType();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     * @return
     *     the new instance of {@link Ref }
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link RespVaeRef }
     * 
     * @return
     *     the new instance of {@link RespVaeRef }
     */
    public RespVaeRef createRespVaeRef() {
        return new RespVaeRef();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     * @return
     *     the new instance of {@link IdentifierType }
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     * @return
     *     the new instance of {@link NameType }
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link MerchantOwnership }
     * 
     * @return
     *     the new instance of {@link MerchantOwnership }
     */
    public MerchantOwnership createMerchantOwnership() {
        return new MerchantOwnership();
    }

    /**
     * Create an instance of {@link MerchantType }
     * 
     * @return
     *     the new instance of {@link MerchantType }
     */
    public MerchantType createMerchantType() {
        return new MerchantType();
    }

    /**
     * Create an instance of {@link InvoiceType }
     * 
     * @return
     *     the new instance of {@link InvoiceType }
     */
    public InvoiceType createInvoiceType() {
        return new InvoiceType();
    }

    /**
     * Create an instance of {@link InstitutionName }
     * 
     * @return
     *     the new instance of {@link InstitutionName }
     */
    public InstitutionName createInstitutionName() {
        return new InstitutionName();
    }

    /**
     * Create an instance of {@link InstitutionPurpose }
     * 
     * @return
     *     the new instance of {@link InstitutionPurpose }
     */
    public InstitutionPurpose createInstitutionPurpose() {
        return new InstitutionPurpose();
    }

    /**
     * Create an instance of {@link InstitutionOriginatorAddress }
     * 
     * @return
     *     the new instance of {@link InstitutionOriginatorAddress }
     */
    public InstitutionOriginatorAddress createInstitutionOriginatorAddress() {
        return new InstitutionOriginatorAddress();
    }

    /**
     * Create an instance of {@link InstitutionOriginator }
     * 
     * @return
     *     the new instance of {@link InstitutionOriginator }
     */
    public InstitutionOriginator createInstitutionOriginator() {
        return new InstitutionOriginator();
    }

    /**
     * Create an instance of {@link InstitutionBeneficiary }
     * 
     * @return
     *     the new instance of {@link InstitutionBeneficiary }
     */
    public InstitutionBeneficiary createInstitutionBeneficiary() {
        return new InstitutionBeneficiary();
    }

    /**
     * Create an instance of {@link InstitutionType }
     * 
     * @return
     *     the new instance of {@link InstitutionType }
     */
    public InstitutionType createInstitutionType() {
        return new InstitutionType();
    }

    /**
     * Create an instance of {@link CurrValType }
     * 
     * @return
     *     the new instance of {@link CurrValType }
     */
    public CurrValType createCurrValType() {
        return new CurrValType();
    }

    /**
     * Create an instance of {@link KeyType }
     * 
     * @return
     *     the new instance of {@link KeyType }
     */
    public KeyType createKeyType() {
        return new KeyType();
    }

    /**
     * Create an instance of {@link MetaType }
     * 
     * @return
     *     the new instance of {@link MetaType }
     */
    public MetaType createMetaType() {
        return new MetaType();
    }

    /**
     * Create an instance of {@link MandateSign }
     * 
     * @return
     *     the new instance of {@link MandateSign }
     */
    public MandateSign createMandateSign() {
        return new MandateSign();
    }

    /**
     * Create an instance of {@link PspVersionType }
     * 
     * @return
     *     the new instance of {@link PspVersionType }
     */
    public PspVersionType createPspVersionType() {
        return new PspVersionType();
    }

    /**
     * Create an instance of {@link PspVersionSupportedType }
     * 
     * @return
     *     the new instance of {@link PspVersionSupportedType }
     */
    public PspVersionSupportedType createPspVersionSupportedType() {
        return new PspVersionSupportedType();
    }

    /**
     * Create an instance of {@link FeatureSupported }
     * 
     * @return
     *     the new instance of {@link FeatureSupported }
     */
    public FeatureSupported createFeatureSupported() {
        return new FeatureSupported();
    }

    /**
     * Create an instance of {@link QrType }
     * 
     * @return
     *     the new instance of {@link QrType }
     */
    public QrType createQrType() {
        return new QrType();
    }

    /**
     * Create an instance of {@link ConsentType }
     * 
     * @return
     *     the new instance of {@link ConsentType }
     */
    public ConsentType createConsentType() {
        return new ConsentType();
    }

    /**
     * Create an instance of {@link MapperConfRefType }
     * 
     * @return
     *     the new instance of {@link MapperConfRefType }
     */
    public MapperConfRefType createMapperConfRefType() {
        return new MapperConfRefType();
    }

    /**
     * Create an instance of {@link Auth }
     * 
     * @return
     *     the new instance of {@link Auth }
     */
    public Auth createAuth() {
        return new Auth();
    }

    /**
     * Create an instance of {@link Uses }
     * 
     * @return
     *     the new instance of {@link Uses }
     */
    public Uses createUses() {
        return new Uses();
    }

    /**
     * Create an instance of {@link com.fss.aeps.jaxb.Meta }
     * 
     * @return
     *     the new instance of {@link com.fss.aeps.jaxb.Meta }
     */
    public com.fss.aeps.jaxb.Meta createMeta() {
        return new com.fss.aeps.jaxb.Meta();
    }

    /**
     * Create an instance of {@link Skey }
     * 
     * @return
     *     the new instance of {@link Skey }
     */
    public Skey createSkey() {
        return new Skey();
    }

    /**
     * Create an instance of {@link Hmac }
     * 
     * @return
     *     the new instance of {@link Hmac }
     */
    public Hmac createHmac() {
        return new Hmac();
    }

    /**
     * Create an instance of {@link com.fss.aeps.jaxb.Data }
     * 
     * @return
     *     the new instance of {@link com.fss.aeps.jaxb.Data }
     */
    public com.fss.aeps.jaxb.Data createData() {
        return new com.fss.aeps.jaxb.Data();
    }

    /**
     * Create an instance of {@link KycReqInfo }
     * 
     * @return
     *     the new instance of {@link KycReqInfo }
     */
    public KycReqInfo createKycReqInfo() {
        return new KycReqInfo();
    }

    /**
     * Create an instance of {@link KycRes }
     * 
     * @return
     *     the new instance of {@link KycRes }
     */
    public KycRes createKycRes() {
        return new KycRes();
    }

    /**
     * Create an instance of {@link TokenizeRes }
     * 
     * @return
     *     the new instance of {@link TokenizeRes }
     */
    public TokenizeRes createTokenizeRes() {
        return new TokenizeRes();
    }

    /**
     * Create an instance of {@link ComplaintType }
     * 
     * @return
     *     the new instance of {@link ComplaintType }
     */
    public ComplaintType createComplaintType() {
        return new ComplaintType();
    }

    /**
     * Create an instance of {@link Otp }
     * 
     * @return
     *     the new instance of {@link Otp }
     */
    public Otp createOtp() {
        return new Otp();
    }

    /**
     * Create an instance of {@link KycInfo }
     * 
     * @return
     *     the new instance of {@link KycInfo }
     */
    public KycInfo createKycInfo() {
        return new KycInfo();
    }

    /**
     * Create an instance of {@link AuthDetails }
     * 
     * @return
     *     the new instance of {@link AuthDetails }
     */
    public AuthDetails createAuthDetails() {
        return new AuthDetails();
    }

    /**
     * Create an instance of {@link SHGInfo.Detail }
     * 
     * @return
     *     the new instance of {@link SHGInfo.Detail }
     */
    public SHGInfo.Detail createSHGInfoDetail() {
        return new SHGInfo.Detail();
    }

    /**
     * Create an instance of {@link MetaListType.Tag }
     * 
     * @return
     *     the new instance of {@link MetaListType.Tag }
     */
    public MetaListType.Tag createMetaListTypeTag() {
        return new MetaListType.Tag();
    }

    /**
     * Create an instance of {@link FxListType.Fx }
     * 
     * @return
     *     the new instance of {@link FxListType.Fx }
     */
    public FxListType.Fx createFxListTypeFx() {
        return new FxListType.Fx();
    }

    /**
     * Create an instance of {@link MandateType.Validity }
     * 
     * @return
     *     the new instance of {@link MandateType.Validity }
     */
    public MandateType.Validity createMandateTypeValidity() {
        return new MandateType.Validity();
    }

    /**
     * Create an instance of {@link MandateType.Amount }
     * 
     * @return
     *     the new instance of {@link MandateType.Amount }
     */
    public MandateType.Amount createMandateTypeAmount() {
        return new MandateType.Amount();
    }

    /**
     * Create an instance of {@link RecurrenceType.Rule }
     * 
     * @return
     *     the new instance of {@link RecurrenceType.Rule }
     */
    public RecurrenceType.Rule createRecurrenceTypeRule() {
        return new RecurrenceType.Rule();
    }

    /**
     * Create an instance of {@link CredsType.Cred.Data }
     * 
     * @return
     *     the new instance of {@link CredsType.Cred.Data }
     */
    public CredsType.Cred.Data createCredsTypeCredData() {
        return new CredsType.Cred.Data();
    }

    /**
     * Create an instance of {@link AccountType.Detail }
     * 
     * @return
     *     the new instance of {@link AccountType.Detail }
     */
    public AccountType.Detail createAccountTypeDetail() {
        return new AccountType.Detail();
    }

    /**
     * Create an instance of {@link IdType.Detail }
     * 
     * @return
     *     the new instance of {@link IdType.Detail }
     */
    public IdType.Detail createIdTypeDetail() {
        return new IdType.Detail();
    }

    /**
     * Create an instance of {@link ReqIdDetails.Id }
     * 
     * @return
     *     the new instance of {@link ReqIdDetails.Id }
     */
    public ReqIdDetails.Id createReqIdDetailsId() {
        return new ReqIdDetails.Id();
    }

    /**
     * Create an instance of {@link RegIdDetailsType.Id }
     * 
     * @return
     *     the new instance of {@link RegIdDetailsType.Id }
     */
    public RegIdDetailsType.Id createRegIdDetailsTypeId() {
        return new RegIdDetailsType.Id();
    }

    /**
     * Create an instance of {@link DeviceType.Tag }
     * 
     * @return
     *     the new instance of {@link DeviceType.Tag }
     */
    public DeviceType.Tag createDeviceTypeTag() {
        return new DeviceType.Tag();
    }

    /**
     * Create an instance of {@link AmountType.Split }
     * 
     * @return
     *     the new instance of {@link AmountType.Split }
     */
    public AmountType.Split createAmountTypeSplit() {
        return new AmountType.Split();
    }

    /**
     * Create an instance of {@link RulesType.Rule }
     * 
     * @return
     *     the new instance of {@link RulesType.Rule }
     */
    public RulesType.Rule createRulesTypeRule() {
        return new RulesType.Rule();
    }

    /**
     * Create an instance of {@link RiskScoresType.Score }
     * 
     * @return
     *     the new instance of {@link RiskScoresType.Score }
     */
    public RiskScoresType.Score createRiskScoresTypeScore() {
        return new RiskScoresType.Score();
    }

    /**
     * Create an instance of {@link ReqPay.Meta.Tag }
     * 
     * @return
     *     the new instance of {@link ReqPay.Meta.Tag }
     */
    public ReqPay.Meta.Tag createReqPayMetaTag() {
        return new ReqPay.Meta.Tag();
    }

    /**
     * Create an instance of {@link ReqOtp.RegDetails.Detail }
     * 
     * @return
     *     the new instance of {@link ReqOtp.RegDetails.Detail }
     */
    public ReqOtp.RegDetails.Detail createReqOtpRegDetailsDetail() {
        return new ReqOtp.RegDetails.Detail();
    }

    /**
     * Create an instance of {@link RespBalEnq.Payer.MiniStatement.StmtData }
     * 
     * @return
     *     the new instance of {@link RespBalEnq.Payer.MiniStatement.StmtData }
     */
    public RespBalEnq.Payer.MiniStatement.StmtData createRespBalEnqPayerMiniStatementStmtData() {
        return new RespBalEnq.Payer.MiniStatement.StmtData();
    }

    /**
     * Create an instance of {@link RespBalEnq.Payer.Bal.Data }
     * 
     * @return
     *     the new instance of {@link RespBalEnq.Payer.Bal.Data }
     */
    public RespBalEnq.Payer.Bal.Data createRespBalEnqPayerBalData() {
        return new RespBalEnq.Payer.Bal.Data();
    }

    /**
     * Create an instance of {@link HeadType.Iso8583Element }
     * 
     * @return
     *     the new instance of {@link HeadType.Iso8583Element }
     */
    public HeadType.Iso8583Element createHeadTypeIso8583Element() {
        return new HeadType.Iso8583Element();
    }

}
