//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for payConstant.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="payConstant">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="PAY"/>
 *     <enumeration value="COLLECT"/>
 *     <enumeration value="REVERSAL"/>
 *     <enumeration value="REFUND"/>
 *     <enumeration value="CREDIT"/>
 *     <enumeration value="DEBIT"/>
 *     <enumeration value="BAL"/>
 *     <enumeration value="ListPsp"/>
 *     <enumeration value="ListAccPvd"/>
 *     <enumeration value="ListKeys"/>
 *     <enumeration value="GetToken"/>
 *     <enumeration value="ListAccount"/>
 *     <enumeration value="ListVae"/>
 *     <enumeration value="ManageVae"/>
 *     <enumeration value="ValAdd"/>
 *     <enumeration value="SetCre"/>
 *     <enumeration value="ReqRegMob"/>
 *     <enumeration value="ResetRegMob"/>
 *     <enumeration value="ChkTxn"/>
 *     <enumeration value="Otp"/>
 *     <enumeration value="BalEnq"/>
 *     <enumeration value="Hbt"/>
 *     <enumeration value="PendingMsg"/>
 *     <enumeration value="TxnConfirmation"/>
 *     <enumeration value="CREATE"/>
 *     <enumeration value="REVOKE"/>
 *     <enumeration value="UPDATE"/>
 *     <enumeration value="ListPSPKeys"/>
 *     <enumeration value="BalChk"/>
 *     <enumeration value="ReqActivation"/>
 *     <enumeration value="International"/>
 *     <enumeration value="UPI Services"/>
 *     <enumeration value="IntlQr"/>
 *     <enumeration value="QrVal"/>
 *     <enumeration value="ReqFxRate"/>
 *     <enumeration value="RespFxRate"/>
 *     <enumeration value="Booking"/>
 *     <enumeration value="ValCust"/>
 *     <enumeration value="ReqMapperConfirmation"/>
 *     <enumeration value="MandateNotification"/>
 *     <enumeration value="FETCH"/>
 *     <enumeration value="RespKyc"/>
 *     <enumeration value="ReqKyc"/>
 *     <enumeration value="AUTH"/>
 *     <enumeration value="PAUSE"/>
 *     <enumeration value="UNPAUSE"/>
 *     <enumeration value="VR"/>
 *     <enumeration value="ChkBankStatus"/>
 *     <enumeration value="NameEnq"/>
 *     <enumeration value="MiniStmt"/>
 *     <enumeration value="BFD"/>
 *     <enumeration value="BIO-AUTH"/>
 *     <enumeration value="DEMO-AUTH"/>
 *     <enumeration value="REQ-OTP"/>
 *     <enumeration value="ADVICE"/>
 *     <enumeration value="OTP-AUTH-UPDATE"/>
 *     <enumeration value="EKYC"/>
 *     <enumeration value="TKN"/>
 *     <enumeration value="PAUSE"/>
 *     <enumeration value="UNPAUSE"/>
 *     <enumeration value="COMPLAINT"/>
 *     <enumeration value="DISPUTE"/>
 *     <enumeration value="STATUSUPDATE"/>
 *     <enumeration value="CHKSTATUS"/>
 *     <enumeration value="STATUS"/>
 *     <enumeration value="AUTOUPDATE"/>
 *     <enumeration value="BACKOFFICE"/>
 *     <enumeration value="ITD"/>
 *     <enumeration value="CMREGISTRATION"/>
 *     <enumeration value="CHECK"/>
 *     <enumeration value="HISTORY"/>
 *     <enumeration value="SHG"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "payConstant")
@XmlEnum
public enum PayConstant {

    PAY("PAY"),
    COLLECT("COLLECT"),
    REVERSAL("REVERSAL"),
    REFUND("REFUND"),
    CREDIT("CREDIT"),
    DEBIT("DEBIT"),
    BAL("BAL"),
    @XmlEnumValue("ListPsp")
    LIST_PSP("ListPsp"),
    @XmlEnumValue("ListAccPvd")
    LIST_ACC_PVD("ListAccPvd"),
    @XmlEnumValue("ListKeys")
    LIST_KEYS("ListKeys"),
    @XmlEnumValue("GetToken")
    GET_TOKEN("GetToken"),
    @XmlEnumValue("ListAccount")
    LIST_ACCOUNT("ListAccount"),
    @XmlEnumValue("ListVae")
    LIST_VAE("ListVae"),
    @XmlEnumValue("ManageVae")
    MANAGE_VAE("ManageVae"),
    @XmlEnumValue("ValAdd")
    VAL_ADD("ValAdd"),
    @XmlEnumValue("SetCre")
    SET_CRE("SetCre"),
    @XmlEnumValue("ReqRegMob")
    REQ_REG_MOB("ReqRegMob"),
    @XmlEnumValue("ResetRegMob")
    RESET_REG_MOB("ResetRegMob"),
    @XmlEnumValue("ChkTxn")
    CHK_TXN("ChkTxn"),
    @XmlEnumValue("Otp")
    OTP("Otp"),
    @XmlEnumValue("BalEnq")
    BAL_ENQ("BalEnq"),
    @XmlEnumValue("Hbt")
    HBT("Hbt"),
    @XmlEnumValue("PendingMsg")
    PENDING_MSG("PendingMsg"),
    @XmlEnumValue("TxnConfirmation")
    TXN_CONFIRMATION("TxnConfirmation"),
    CREATE("CREATE"),
    REVOKE("REVOKE"),
    UPDATE("UPDATE"),
    @XmlEnumValue("ListPSPKeys")
    LIST_PSP_KEYS("ListPSPKeys"),
    @XmlEnumValue("BalChk")
    BAL_CHK("BalChk"),
    @XmlEnumValue("ReqActivation")
    REQ_ACTIVATION("ReqActivation"),
    @XmlEnumValue("International")
    INTERNATIONAL("International"),
    @XmlEnumValue("UPI Services")
    UPI_SERVICES("UPI Services"),
    @XmlEnumValue("IntlQr")
    INTL_QR("IntlQr"),
    @XmlEnumValue("QrVal")
    QR_VAL("QrVal"),
    @XmlEnumValue("ReqFxRate")
    REQ_FX_RATE("ReqFxRate"),
    @XmlEnumValue("RespFxRate")
    RESP_FX_RATE("RespFxRate"),
    @XmlEnumValue("Booking")
    BOOKING("Booking"),
    @XmlEnumValue("ValCust")
    VAL_CUST("ValCust"),
    @XmlEnumValue("ReqMapperConfirmation")
    REQ_MAPPER_CONFIRMATION("ReqMapperConfirmation"),
    @XmlEnumValue("MandateNotification")
    MANDATE_NOTIFICATION("MandateNotification"),
    FETCH("FETCH"),
    @XmlEnumValue("RespKyc")
    RESP_KYC("RespKyc"),
    @XmlEnumValue("ReqKyc")
    REQ_KYC("ReqKyc"),
    AUTH("AUTH"),
    PAUSE("PAUSE"),
    UNPAUSE("UNPAUSE"),
    VR("VR"),
    @XmlEnumValue("ChkBankStatus")
    CHK_BANK_STATUS("ChkBankStatus"),
    @XmlEnumValue("NameEnq")
    NAME_ENQ("NameEnq"),
    @XmlEnumValue("MiniStmt")
    MINI_STMT("MiniStmt"),
    BFD("BFD"),
    @XmlEnumValue("BIO-AUTH")
    BIO_AUTH("BIO-AUTH"),
    @XmlEnumValue("DEMO-AUTH")
    DEMO_AUTH("DEMO-AUTH"),
    @XmlEnumValue("REQ-OTP")
    REQ_OTP("REQ-OTP"),
    ADVICE("ADVICE"),
    @XmlEnumValue("OTP-AUTH-UPDATE")
    OTP_AUTH_UPDATE("OTP-AUTH-UPDATE"),
    EKYC("EKYC"),
    TKN("TKN"),
    COMPLAINT("COMPLAINT"),
    DISPUTE("DISPUTE"),
    STATUSUPDATE("STATUSUPDATE"),
    CHKSTATUS("CHKSTATUS"),
    STATUS("STATUS"),
    AUTOUPDATE("AUTOUPDATE"),
    BACKOFFICE("BACKOFFICE"),
    ITD("ITD"),
    CMREGISTRATION("CMREGISTRATION"),
    CHECK("CHECK"),
    HISTORY("HISTORY"),
    SHG("SHG");
    private final String value;

    PayConstant(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PayConstant fromValue(String v) {
        for (PayConstant c: PayConstant.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
