//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import java.util.Date;

import com.fss.aeps.jaxb.adapter.JaxbDateAdapter;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for payeeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="payeeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Info" type="{http://npci.org/upi/schema/}infoType" minOccurs="0"/&gt;
 *         &lt;element name="Device" type="{http://npci.org/upi/schema/}deviceType" minOccurs="0"/&gt;
 *         &lt;element name="Ac" type="{http://npci.org/upi/schema/}accountType" minOccurs="0"/&gt;
 *         &lt;element name="Amount" type="{http://npci.org/upi/schema/}amountType" minOccurs="0"/&gt;
 *         &lt;element name="Merchant" type="{http://npci.org/upi/schema/}merchantType" minOccurs="0"/&gt;
 *         &lt;element name="Institution" type="{http://npci.org/upi/schema/}institutionType" minOccurs="0"/&gt;
 *         &lt;element name="FxList" type="{http://npci.org/upi/schema/}fxListType" minOccurs="0"/&gt;
 *         &lt;element name="Consent" type="{http://npci.org/upi/schema/}consentType" minOccurs="0"/&gt;
 *         &lt;element name="ReqIdDetails" type="{http://npci.org/upi/schema/}reqIdDetails" minOccurs="0"/&gt;
 *         &lt;element name="Creds" type="{http://npci.org/upi/schema/}credsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" type="{http://npci.org/upi/schema/}payerConstant" /&gt;
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="note" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ts" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cmId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "payeeType", propOrder = {
    "info",
    "device",
    "ac",
    "amount",
    "merchant",
    "institution",
    "fxList",
    "consent",
    "reqIdDetails",
    "creds"
})
public class PayeeType {

    @XmlElement(name = "Info")
    protected InfoType info;
    @XmlElement(name = "Device")
    protected DeviceType device;
    @XmlElement(name = "Ac")
    protected AccountType ac;
    @XmlElement(name = "Amount")
    protected AmountType amount;
    @XmlElement(name = "Merchant")
    protected MerchantType merchant;
    @XmlElement(name = "Institution")
    protected InstitutionType institution;
    @XmlElement(name = "FxList")
    protected FxListType fxList;
    @XmlElement(name = "Consent")
    protected ConsentType consent;
    @XmlElement(name = "ReqIdDetails")
    protected ReqIdDetails reqIdDetails;
    @XmlElement(name = "Creds")
    protected CredsType creds;
    @XmlAttribute(name = "addr")
    protected String addr;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "seqNum")
    protected int seqNum;
    @XmlAttribute(name = "type")
    protected PayerConstant type;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "note")
    protected String note;
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    @XmlAttribute(name = "ts")
    protected Date ts;
    @XmlAttribute(name = "cmId")
    protected String cmId;

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link InfoType }
     *     
     */
    public InfoType getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoType }
     *     
     */
    public void setInfo(InfoType value) {
        this.info = value;
    }

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceType }
     *     
     */
    public DeviceType getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceType }
     *     
     */
    public void setDevice(DeviceType value) {
        this.device = value;
    }

    /**
     * Gets the value of the ac property.
     * 
     * @return
     *     possible object is
     *     {@link AccountType }
     *     
     */
    public AccountType getAc() {
        return ac;
    }

    /**
     * Sets the value of the ac property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountType }
     *     
     */
    public void setAc(AccountType value) {
        this.ac = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmount(AmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the merchant property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantType }
     *     
     */
    public MerchantType getMerchant() {
        return merchant;
    }

    /**
     * Sets the value of the merchant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantType }
     *     
     */
    public void setMerchant(MerchantType value) {
        this.merchant = value;
    }

    /**
     * Gets the value of the institution property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionType }
     *     
     */
    public InstitutionType getInstitution() {
        return institution;
    }

    /**
     * Sets the value of the institution property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionType }
     *     
     */
    public void setInstitution(InstitutionType value) {
        this.institution = value;
    }

    /**
     * Gets the value of the fxList property.
     * 
     * @return
     *     possible object is
     *     {@link FxListType }
     *     
     */
    public FxListType getFxList() {
        return fxList;
    }

    /**
     * Sets the value of the fxList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxListType }
     *     
     */
    public void setFxList(FxListType value) {
        this.fxList = value;
    }

    /**
     * Gets the value of the consent property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentType }
     *     
     */
    public ConsentType getConsent() {
        return consent;
    }

    /**
     * Sets the value of the consent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentType }
     *     
     */
    public void setConsent(ConsentType value) {
        this.consent = value;
    }

    /**
     * Gets the value of the reqIdDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ReqIdDetails }
     *     
     */
    public ReqIdDetails getReqIdDetails() {
        return reqIdDetails;
    }

    /**
     * Sets the value of the reqIdDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReqIdDetails }
     *     
     */
    public void setReqIdDetails(ReqIdDetails value) {
        this.reqIdDetails = value;
    }

    /**
     * Gets the value of the creds property.
     * 
     * @return
     *     possible object is
     *     {@link CredsType }
     *     
     */
    public CredsType getCreds() {
        return creds;
    }

    /**
     * Sets the value of the creds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredsType }
     *     
     */
    public void setCreds(CredsType value) {
        this.creds = value;
    }

    /**
     * Gets the value of the addr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr(String value) {
        this.addr = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public int getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqNum(int value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link PayerConstant }
     *     
     */
    public PayerConstant getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerConstant }
     *     
     */
    public void setType(PayerConstant value) {
        this.type = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTs(Date value) {
        this.ts = value;
    }

    /**
     * Gets the value of the cmId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmId() {
        return cmId;
    }

    /**
     * Sets the value of the cmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmId(String value) {
        this.cmId = value;
    }

}
