//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pspVersionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pspVersionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="no" type="{http://npci.org/upi/schema/}pspVersionNo" /&gt;
 *       &lt;attribute name="description" type="{http://npci.org/upi/schema/}pspVersionDesc" /&gt;
 *       &lt;attribute name="mandatory" type="{http://npci.org/upi/schema/}pspVersionMandatory" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pspVersionType")
public class PspVersionType {

    @XmlAttribute(name = "no")
    protected String no;
    @XmlAttribute(name = "description")
    protected PspVersionDesc description;
    @XmlAttribute(name = "mandatory")
    protected PspVersionMandatory mandatory;

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNo(String value) {
        this.no = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link PspVersionDesc }
     *     
     */
    public PspVersionDesc getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link PspVersionDesc }
     *     
     */
    public void setDescription(PspVersionDesc value) {
        this.description = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     * @return
     *     possible object is
     *     {@link PspVersionMandatory }
     *     
     */
    public PspVersionMandatory getMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link PspVersionMandatory }
     *     
     */
    public void setMandatory(PspVersionMandatory value) {
        this.mandatory = value;
    }

}
