//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for qrType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="qrType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="qVer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="ts" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="qrMedium" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="expireTs" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="query" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="verToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="stan" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="acqInstCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "qrType")
public class QrType {

    @XmlAttribute(name = "qVer")
    protected String qVer;
    @XmlAttribute(name = "ts")
    protected String ts;
    @XmlAttribute(name = "qrMedium")
    protected String qrMedium;
    @XmlAttribute(name = "expireTs")
    protected String expireTs;
    @XmlAttribute(name = "query")
    protected String query;
    @XmlAttribute(name = "verToken")
    protected String verToken;
    @XmlAttribute(name = "stan")
    protected String stan;
    @XmlAttribute(name = "acqInstCode")
    protected String acqInstCode;

    /**
     * Gets the value of the qVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQVer() {
        return qVer;
    }

    /**
     * Sets the value of the qVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQVer(String value) {
        this.qVer = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the qrMedium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrMedium() {
        return qrMedium;
    }

    /**
     * Sets the value of the qrMedium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrMedium(String value) {
        this.qrMedium = value;
    }

    /**
     * Gets the value of the expireTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireTs() {
        return expireTs;
    }

    /**
     * Sets the value of the expireTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireTs(String value) {
        this.expireTs = value;
    }

    /**
     * Gets the value of the query property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuery() {
        return query;
    }

    /**
     * Sets the value of the query property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuery(String value) {
        this.query = value;
    }

    /**
     * Gets the value of the verToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerToken() {
        return verToken;
    }

    /**
     * Sets the value of the verToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerToken(String value) {
        this.verToken = value;
    }

    /**
     * Gets the value of the stan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStan() {
        return stan;
    }

    /**
     * Sets the value of the stan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStan(String value) {
        this.stan = value;
    }

    /**
     * Gets the value of the acqInstCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcqInstCode() {
        return acqInstCode;
    }

    /**
     * Sets the value of the acqInstCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcqInstCode(String value) {
        this.acqInstCode = value;
    }

}
