//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recurrencePatternType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="recurrencePatternType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ONETIME"/&gt;
 *     &lt;enumeration value="DAILY"/&gt;
 *     &lt;enumeration value="WEEKLY"/&gt;
 *     &lt;enumeration value="FORTNIGHTLY"/&gt;
 *     &lt;enumeration value="MONTHLY"/&gt;
 *     &lt;enumeration value="BIMONTHLY"/&gt;
 *     &lt;enumeration value="QUARTERLY"/&gt;
 *     &lt;enumeration value="HALFYEARLY"/&gt;
 *     &lt;enumeration value="YEARLY"/&gt;
 *     &lt;enumeration value="ASPRESENTED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "recurrencePatternType")
@XmlEnum
public enum RecurrencePatternType {

    ONETIME,
    DAILY,
    WEEKLY,
    FORTNIGHTLY,
    MONTHLY,
    BIMONTHLY,
    QUARTERLY,
    HALFYEARLY,
    YEARLY,
    ASPRESENTED;

    public String value() {
        return name();
    }

    public static RecurrencePatternType fromValue(String v) {
        return valueOf(v);
    }

}
