//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recurrencePatternType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="recurrencePatternType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="ONETIME"/>
 *     <enumeration value="DAILY"/>
 *     <enumeration value="WEEKLY"/>
 *     <enumeration value="FORTNIGHTLY"/>
 *     <enumeration value="MONTHLY"/>
 *     <enumeration value="BIMONTHLY"/>
 *     <enumeration value="QUARTERLY"/>
 *     <enumeration value="HALFYEARLY"/>
 *     <enumeration value="YEARLY"/>
 *     <enumeration value="ASPRESENTED"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "recurrencePatternType")
@XmlEnum
public enum RecurrencePatternType {

    ONETIME,
    DAILY,
    WEEKLY,
    FORTNIGHTLY,
    MONTHLY,
    BIMONTHLY,
    QUARTERLY,
    HALFYEARLY,
    YEARLY,
    ASPRESENTED;

    public String value() {
        return name();
    }

    public static RecurrencePatternType fromValue(String v) {
        return valueOf(v);
    }

}
