//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for regIdStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="regIdStatusType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="BLOCKED"/>
 *     <enumeration value="ACTIVE"/>
 *     <enumeration value="INACTIVE"/>
 *     <enumeration value="NEW"/>
 *     <enumeration value="DEREGISTER"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "regIdStatusType")
@XmlEnum
public enum RegIdStatusType {

    BLOCKED,
    ACTIVE,
    INACTIVE,
    NEW,
    DEREGISTER;

    public String value() {
        return name();
    }

    public static RegIdStatusType fromValue(String v) {
        return valueOf(v);
    }

}
