//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for regIdDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="regIdDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" maxOccurs="2"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="name" use="required" type="{http://npci.org/upi/schema/}regIdDetailsTagNameType" /&gt;
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="setStatus" type="{http://npci.org/upi/schema/}regIdDetailsSetStatusType" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" type="{http://npci.org/upi/schema/}payerConstant" /&gt;
 *       &lt;attribute name="idStatus" type="{http://npci.org/upi/schema/}regIdStatusType" /&gt;
 *       &lt;attribute name="lastUpdatedTs" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="channel" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "regIdDetailsType", propOrder = {
    "id"
})
public class RegIdDetailsType {

    @XmlElement(name = "Id", required = true)
    protected List<RegIdDetailsType.Id> id;
    @XmlAttribute(name = "addr")
    protected String addr;
    @XmlAttribute(name = "type")
    protected PayerConstant type;
    @XmlAttribute(name = "idStatus")
    protected RegIdStatusType idStatus;
    @XmlAttribute(name = "lastUpdatedTs")
    protected String lastUpdatedTs;
    @XmlAttribute(name = "channel")
    protected String channel;

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegIdDetailsType.Id }
     * 
     * 
     */
    public List<RegIdDetailsType.Id> getId() {
        if (id == null) {
            id = new ArrayList<RegIdDetailsType.Id>();
        }
        return this.id;
    }

    /**
     * Gets the value of the addr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr(String value) {
        this.addr = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link PayerConstant }
     *     
     */
    public PayerConstant getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerConstant }
     *     
     */
    public void setType(PayerConstant value) {
        this.type = value;
    }

    /**
     * Gets the value of the idStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RegIdStatusType }
     *     
     */
    public RegIdStatusType getIdStatus() {
        return idStatus;
    }

    /**
     * Sets the value of the idStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegIdStatusType }
     *     
     */
    public void setIdStatus(RegIdStatusType value) {
        this.idStatus = value;
    }

    /**
     * Gets the value of the lastUpdatedTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedTs() {
        return lastUpdatedTs;
    }

    /**
     * Sets the value of the lastUpdatedTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedTs(String value) {
        this.lastUpdatedTs = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="name" use="required" type="{http://npci.org/upi/schema/}regIdDetailsTagNameType" /&gt;
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="setStatus" type="{http://npci.org/upi/schema/}regIdDetailsSetStatusType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Id {

        @XmlAttribute(name = "name", required = true)
        protected RegIdDetailsTagNameType name;
        @XmlAttribute(name = "value", required = true)
        protected String value;
        @XmlAttribute(name = "setStatus")
        protected RegIdDetailsSetStatusType setStatus;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link RegIdDetailsTagNameType }
         *     
         */
        public RegIdDetailsTagNameType getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link RegIdDetailsTagNameType }
         *     
         */
        public void setName(RegIdDetailsTagNameType value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the setStatus property.
         * 
         * @return
         *     possible object is
         *     {@link RegIdDetailsSetStatusType }
         *     
         */
        public RegIdDetailsSetStatusType getSetStatus() {
            return setStatus;
        }

        /**
         * Sets the value of the setStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link RegIdDetailsSetStatusType }
         *     
         */
        public void setSetStatus(RegIdDetailsSetStatusType value) {
            this.setStatus = value;
        }

    }

}
