//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 02:25:14 PM IST 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="repId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="repName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="authId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="authName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="txnType" type="{http://npci.org/upi/schema/}txnType" /&gt;
 *       &lt;attribute name="amt" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fndIndi" type="{http://npci.org/upi/schema/}fndIndi" /&gt;
 *       &lt;attribute name="channel" type="{http://npci.org/upi/schema/}channelType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reInfoType")
public class ReInfoType {

    @XmlAttribute(name = "repId", required = true)
    protected String repId;
    @XmlAttribute(name = "repName")
    protected String repName;
    @XmlAttribute(name = "authId", required = true)
    protected String authId;
    @XmlAttribute(name = "authName")
    protected String authName;
    @XmlAttribute(name = "txnType")
    protected TxnType txnType;
    @XmlAttribute(name = "amt")
    protected String amt;
    @XmlAttribute(name = "fndIndi")
    protected FndIndi fndIndi;
    @XmlAttribute(name = "channel")
    protected ChannelType channel;

    /**
     * Gets the value of the repId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepId() {
        return repId;
    }

    /**
     * Sets the value of the repId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepId(String value) {
        this.repId = value;
    }

    /**
     * Gets the value of the repName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepName() {
        return repName;
    }

    /**
     * Sets the value of the repName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepName(String value) {
        this.repName = value;
    }

    /**
     * Gets the value of the authId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * Sets the value of the authId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthId(String value) {
        this.authId = value;
    }

    /**
     * Gets the value of the authName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * Sets the value of the authName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthName(String value) {
        this.authName = value;
    }

    /**
     * Gets the value of the txnType property.
     * 
     * @return
     *     possible object is
     *     {@link TxnType }
     *     
     */
    public TxnType getTxnType() {
        return txnType;
    }

    /**
     * Sets the value of the txnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnType }
     *     
     */
    public void setTxnType(TxnType value) {
        this.txnType = value;
    }

    /**
     * Gets the value of the amt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmt() {
        return amt;
    }

    /**
     * Sets the value of the amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmt(String value) {
        this.amt = value;
    }

    /**
     * Gets the value of the fndIndi property.
     * 
     * @return
     *     possible object is
     *     {@link FndIndi }
     *     
     */
    public FndIndi getFndIndi() {
        return fndIndi;
    }

    /**
     * Sets the value of the fndIndi property.
     * 
     * @param value
     *     allowed object is
     *     {@link FndIndi }
     *     
     */
    public void setFndIndi(FndIndi value) {
        this.fndIndi = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link ChannelType }
     *     
     */
    public ChannelType getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChannelType }
     *     
     */
    public void setChannel(ChannelType value) {
        this.channel = value;
    }

}
