//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for respTypeValCust complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="respTypeValCust">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="RespIdDetails" type="{http://npci.org/upi/schema/}respIdDetails" minOccurs="0"/>
 *         <element name="Amount" type="{http://npci.org/upi/schema/}amountType" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="reqMsgId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="result" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="errCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "respTypeValCust", propOrder = {
    "respIdDetails",
    "amount"
})
public class RespTypeValCust {

    @XmlElement(name = "RespIdDetails")
    protected RespIdDetails respIdDetails;
    @XmlElement(name = "Amount")
    protected AmountType amount;
    @XmlAttribute(name = "reqMsgId")
    protected String reqMsgId;
    @XmlAttribute(name = "result")
    protected String result;
    @XmlAttribute(name = "errCode")
    protected String errCode;

    /**
     * Gets the value of the respIdDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RespIdDetails }
     *     
     */
    public RespIdDetails getRespIdDetails() {
        return respIdDetails;
    }

    /**
     * Sets the value of the respIdDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespIdDetails }
     *     
     */
    public void setRespIdDetails(RespIdDetails value) {
        this.respIdDetails = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmount(AmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the reqMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqMsgId() {
        return reqMsgId;
    }

    /**
     * Sets the value of the reqMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqMsgId(String value) {
        this.reqMsgId = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResult(String value) {
        this.result = value;
    }

    /**
     * Gets the value of the errCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * Sets the value of the errCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrCode(String value) {
        this.errCode = value;
    }

}
