//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Head" type="{http://npci.org/upi/schema/}headType"/>
 *         <element name="Resp" type="{http://npci.org/upi/schema/}respType"/>
 *         <element name="Txn" type="{http://npci.org/upi/schema/}payTrans"/>
 *         <element name="Payer">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Bal">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="Data">
 *                               <complexType>
 *                                 <simpleContent>
 *                                   <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                                     <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     <attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   </extension>
 *                                 </simpleContent>
 *                               </complexType>
 *                             </element>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="MiniStatement">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="StmtData" maxOccurs="10">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     <attribute name="seqName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     <attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                           </sequence>
 *                           <attribute name="beneMas" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           <attribute name="stmtLineCount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 <attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 <attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 <attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "resp",
    "txn",
    "payer"
})
@XmlRootElement(name = "RespBalEnq")
public class RespBalEnq {

    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "Resp", required = true)
    protected RespType resp;
    @XmlElement(name = "Txn", required = true)
    protected PayTrans txn;
    @XmlElement(name = "Payer", required = true)
    protected RespBalEnq.Payer payer;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link HeadType }
     *     
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadType }
     *     
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the resp property.
     * 
     * @return
     *     possible object is
     *     {@link RespType }
     *     
     */
    public RespType getResp() {
        return resp;
    }

    /**
     * Sets the value of the resp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespType }
     *     
     */
    public void setResp(RespType value) {
        this.resp = value;
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link PayTrans }
     *     
     */
    public PayTrans getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayTrans }
     *     
     */
    public void setTxn(PayTrans value) {
        this.txn = value;
    }

    /**
     * Gets the value of the payer property.
     * 
     * @return
     *     possible object is
     *     {@link RespBalEnq.Payer }
     *     
     */
    public RespBalEnq.Payer getPayer() {
        return payer;
    }

    /**
     * Sets the value of the payer property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespBalEnq.Payer }
     *     
     */
    public void setPayer(RespBalEnq.Payer value) {
        this.payer = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Bal">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="Data">
     *                     <complexType>
     *                       <simpleContent>
     *                         <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *                           <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           <attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         </extension>
     *                       </simpleContent>
     *                     </complexType>
     *                   </element>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="MiniStatement">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="StmtData" maxOccurs="10">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           <attribute name="seqName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           <attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                 </sequence>
     *                 <attribute name="beneMas" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 <attribute name="stmtLineCount" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *       <attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       <attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       <attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       <attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bal",
        "miniStatement"
    })
    public static class Payer {

        @XmlElement(name = "Bal", required = true)
        protected RespBalEnq.Payer.Bal bal;
        @XmlElement(name = "MiniStatement", required = true)
        protected RespBalEnq.Payer.MiniStatement miniStatement;
        @XmlAttribute(name = "addr")
        protected String addr;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "seqNum")
        protected String seqNum;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "code")
        protected String code;

        /**
         * Gets the value of the bal property.
         * 
         * @return
         *     possible object is
         *     {@link RespBalEnq.Payer.Bal }
         *     
         */
        public RespBalEnq.Payer.Bal getBal() {
            return bal;
        }

        /**
         * Sets the value of the bal property.
         * 
         * @param value
         *     allowed object is
         *     {@link RespBalEnq.Payer.Bal }
         *     
         */
        public void setBal(RespBalEnq.Payer.Bal value) {
            this.bal = value;
        }

        /**
         * Gets the value of the miniStatement property.
         * 
         * @return
         *     possible object is
         *     {@link RespBalEnq.Payer.MiniStatement }
         *     
         */
        public RespBalEnq.Payer.MiniStatement getMiniStatement() {
            return miniStatement;
        }

        /**
         * Sets the value of the miniStatement property.
         * 
         * @param value
         *     allowed object is
         *     {@link RespBalEnq.Payer.MiniStatement }
         *     
         */
        public void setMiniStatement(RespBalEnq.Payer.MiniStatement value) {
            this.miniStatement = value;
        }

        /**
         * Gets the value of the addr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddr() {
            return addr;
        }

        /**
         * Sets the value of the addr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddr(String value) {
            this.addr = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the seqNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeqNum() {
            return seqNum;
        }

        /**
         * Sets the value of the seqNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeqNum(String value) {
            this.seqNum = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="Data">
         *           <complexType>
         *             <simpleContent>
         *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
         *                 <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 <attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               </extension>
         *             </simpleContent>
         *           </complexType>
         *         </element>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "data"
        })
        public static class Bal {

            @XmlElement(name = "Data", required = true)
            protected RespBalEnq.Payer.Bal.Data data;

            /**
             * Gets the value of the data property.
             * 
             * @return
             *     possible object is
             *     {@link RespBalEnq.Payer.Bal.Data }
             *     
             */
            public RespBalEnq.Payer.Bal.Data getData() {
                return data;
            }

            /**
             * Sets the value of the data property.
             * 
             * @param value
             *     allowed object is
             *     {@link RespBalEnq.Payer.Bal.Data }
             *     
             */
            public void setData(RespBalEnq.Payer.Bal.Data value) {
                this.data = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <simpleContent>
             *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
             *       <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       <attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     </extension>
             *   </simpleContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Data {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "code")
                protected String code;
                @XmlAttribute(name = "ki")
                protected String ki;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the ki property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getKi() {
                    return ki;
                }

                /**
                 * Sets the value of the ki property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setKi(String value) {
                    this.ki = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="StmtData" maxOccurs="10">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 <attribute name="seqName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 <attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *       </sequence>
         *       <attribute name="beneMas" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       <attribute name="stmtLineCount" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "stmtData"
        })
        public static class MiniStatement {

            @XmlElement(name = "StmtData", required = true)
            protected List<RespBalEnq.Payer.MiniStatement.StmtData> stmtData;
            @XmlAttribute(name = "beneMas")
            protected String beneMas;
            @XmlAttribute(name = "stmtLineCount")
            protected String stmtLineCount;

            /**
             * Gets the value of the stmtData property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a {@code set} method for the stmtData property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStmtData().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RespBalEnq.Payer.MiniStatement.StmtData }
             * 
             * 
             * @return
             *     The value of the stmtData property.
             */
            public List<RespBalEnq.Payer.MiniStatement.StmtData> getStmtData() {
                if (stmtData == null) {
                    stmtData = new ArrayList<>();
                }
                return this.stmtData;
            }

            /**
             * Gets the value of the beneMas property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBeneMas() {
                return beneMas;
            }

            /**
             * Sets the value of the beneMas property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBeneMas(String value) {
                this.beneMas = value;
            }

            /**
             * Gets the value of the stmtLineCount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStmtLineCount() {
                return stmtLineCount;
            }

            /**
             * Sets the value of the stmtLineCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStmtLineCount(String value) {
                this.stmtLineCount = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <attribute name="seqName" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       <attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class StmtData {

                @XmlAttribute(name = "seqName")
                protected String seqName;
                @XmlAttribute(name = "value")
                protected String value;

                /**
                 * Gets the value of the seqName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSeqName() {
                    return seqName;
                }

                /**
                 * Sets the value of the seqName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSeqName(String value) {
                    this.seqName = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }

    }

}
