//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SHGInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="SHGInfo">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Detail" maxOccurs="50" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 <attribute name="type" type="{http://npci.org/upi/schema/}signatoryTypeEnum" />
 *                 <attribute name="UIDToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 <attribute name="custRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SHGInfo", propOrder = {
    "detail"
})
public class SHGInfo {

    @XmlElement(name = "Detail")
    protected List<SHGInfo.Detail> detail;

    /**
     * Gets the value of the detail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the detail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SHGInfo.Detail }
     * 
     * 
     * @return
     *     The value of the detail property.
     */
    public List<SHGInfo.Detail> getDetail() {
        if (detail == null) {
            detail = new ArrayList<>();
        }
        return this.detail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       <attribute name="type" type="{http://npci.org/upi/schema/}signatoryTypeEnum" />
     *       <attribute name="UIDToken" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       <attribute name="custRef" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Detail {

        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "type")
        protected SignatoryTypeEnum type;
        @XmlAttribute(name = "UIDToken")
        protected String uidToken;
        @XmlAttribute(name = "custRef")
        protected String custRef;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link SignatoryTypeEnum }
         *     
         */
        public SignatoryTypeEnum getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link SignatoryTypeEnum }
         *     
         */
        public void setType(SignatoryTypeEnum value) {
            this.type = value;
        }

        /**
         * Gets the value of the uidToken property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUIDToken() {
            return uidToken;
        }

        /**
         * Sets the value of the uidToken property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUIDToken(String value) {
            this.uidToken = value;
        }

        /**
         * Gets the value of the custRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustRef() {
            return custRef;
        }

        /**
         * Sets the value of the custRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustRef(String value) {
            this.custRef = value;
        }

    }

}
