//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for signatoryTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="signatoryTypeEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Signatory1"/>
 *     <enumeration value="Signatory2"/>
 *     <enumeration value="Signatory3"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "signatoryTypeEnum")
@XmlEnum
public enum SignatoryTypeEnum {

    @XmlEnumValue("Signatory1")
    SIGNATORY_1("Signatory1"),
    @XmlEnumValue("Signatory2")
    SIGNATORY_2("Signatory2"),
    @XmlEnumValue("Signatory3")
    SIGNATORY_3("Signatory3");
    private final String value;

    SignatoryTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SignatoryTypeEnum fromValue(String v) {
        for (SignatoryTypeEnum c: SignatoryTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
