//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tenorConstants.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="tenorConstants">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="TODAY"/>
 *     <enumeration value="TOM"/>
 *     <enumeration value="SPOT"/>
 *     <enumeration value="D1"/>
 *     <enumeration value="W1"/>
 *     <enumeration value="M1"/>
 *     <enumeration value="M2"/>
 *     <enumeration value="M3"/>
 *     <enumeration value="M4"/>
 *     <enumeration value="M5"/>
 *     <enumeration value="M6"/>
 *     <enumeration value="M9"/>
 *     <enumeration value="Y1"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "tenorConstants")
@XmlEnum
public enum TenorConstants {

    TODAY("TODAY"),
    TOM("TOM"),
    SPOT("SPOT"),
    @XmlEnumValue("D1")
    D_1("D1"),
    @XmlEnumValue("W1")
    W_1("W1"),
    @XmlEnumValue("M1")
    M_1("M1"),
    @XmlEnumValue("M2")
    M_2("M2"),
    @XmlEnumValue("M3")
    M_3("M3"),
    @XmlEnumValue("M4")
    M_4("M4"),
    @XmlEnumValue("M5")
    M_5("M5"),
    @XmlEnumValue("M6")
    M_6("M6"),
    @XmlEnumValue("M9")
    M_9("M9"),
    @XmlEnumValue("Y1")
    Y_1("Y1");
    private final String value;

    TenorConstants(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TenorConstants fromValue(String v) {
        for (TenorConstants c: TenorConstants.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
