//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tokenizeRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="tokenizeRes">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Skey" type="{http://npci.org/upi/schema/}Skey" minOccurs="0"/>
 *         <element name="Data" type="{http://npci.org/upi/schema/}Data" minOccurs="0"/>
 *         <element name="Hmac" type="{http://npci.org/upi/schema/}Hmac" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tokenizeRes", propOrder = {
    "skey",
    "data",
    "hmac"
})
public class TokenizeRes {

    @XmlElement(name = "Skey")
    protected Skey skey;
    @XmlElement(name = "Data")
    protected Data data;
    @XmlElement(name = "Hmac")
    protected Hmac hmac;

    /**
     * Gets the value of the skey property.
     * 
     * @return
     *     possible object is
     *     {@link Skey }
     *     
     */
    public Skey getSkey() {
        return skey;
    }

    /**
     * Sets the value of the skey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Skey }
     *     
     */
    public void setSkey(Skey value) {
        this.skey = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setData(Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the hmac property.
     * 
     * @return
     *     possible object is
     *     {@link Hmac }
     *     
     */
    public Hmac getHmac() {
        return hmac;
    }

    /**
     * Sets the value of the hmac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hmac }
     *     
     */
    public void setHmac(Hmac value) {
        this.hmac = value;
    }

}
