//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txnConfirmationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="txnConfirmationType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Refs" type="{http://npci.org/upi/schema/}mapperConfRefType" minOccurs="0"/>
 *         <element name="Consent" type="{http://npci.org/upi/schema/}consentType" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="note" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="orgStatus" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="orgErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="op" use="required" type="{http://npci.org/upi/schema/}opType" />
 *       <attribute name="idType" use="required" type="{http://npci.org/upi/schema/}mapperIdType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "txnConfirmationType", propOrder = {
    "refs",
    "consent"
})
public class TxnConfirmationType {

    @XmlElement(name = "Refs")
    protected MapperConfRefType refs;
    @XmlElement(name = "Consent")
    protected ConsentType consent;
    @XmlAttribute(name = "note")
    protected String note;
    @XmlAttribute(name = "orgStatus", required = true)
    protected String orgStatus;
    @XmlAttribute(name = "orgErrorCode")
    protected String orgErrorCode;
    @XmlAttribute(name = "op", required = true)
    protected OpType op;
    @XmlAttribute(name = "idType", required = true)
    protected MapperIdType idType;

    /**
     * Gets the value of the refs property.
     * 
     * @return
     *     possible object is
     *     {@link MapperConfRefType }
     *     
     */
    public MapperConfRefType getRefs() {
        return refs;
    }

    /**
     * Sets the value of the refs property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapperConfRefType }
     *     
     */
    public void setRefs(MapperConfRefType value) {
        this.refs = value;
    }

    /**
     * Gets the value of the consent property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentType }
     *     
     */
    public ConsentType getConsent() {
        return consent;
    }

    /**
     * Sets the value of the consent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentType }
     *     
     */
    public void setConsent(ConsentType value) {
        this.consent = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the orgStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgStatus() {
        return orgStatus;
    }

    /**
     * Sets the value of the orgStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgStatus(String value) {
        this.orgStatus = value;
    }

    /**
     * Gets the value of the orgErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgErrorCode() {
        return orgErrorCode;
    }

    /**
     * Sets the value of the orgErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgErrorCode(String value) {
        this.orgErrorCode = value;
    }

    /**
     * Gets the value of the op property.
     * 
     * @return
     *     possible object is
     *     {@link OpType }
     *     
     */
    public OpType getOp() {
        return op;
    }

    /**
     * Sets the value of the op property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpType }
     *     
     */
    public void setOp(OpType value) {
        this.op = value;
    }

    /**
     * Gets the value of the idType property.
     * 
     * @return
     *     possible object is
     *     {@link MapperIdType }
     *     
     */
    public MapperIdType getIdType() {
        return idType;
    }

    /**
     * Sets the value of the idType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapperIdType }
     *     
     */
    public void setIdType(MapperIdType value) {
        this.idType = value;
    }

}
