//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txnSubType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="txnSubType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="PAY"/>
 *     <enumeration value="COLLECT"/>
 *     <enumeration value="DEBIT"/>
 *     <enumeration value="CREDIT"/>
 *     <enumeration value="REFUND"/>
 *     <enumeration value="REVERSAL"/>
 *     <enumeration value="MANDATE"/>
 *     <enumeration value="CREATE"/>
 *     <enumeration value="UPDATE"/>
 *     <enumeration value="REVOKE"/>
 *     <enumeration value="PAUSE"/>
 *     <enumeration value="UNPAUSE"/>
 *     <enumeration value="TXN"/>
 *     <enumeration value="DISPUTE"/>
 *     <enumeration value="TXNDISPUTE"/>
 *     <enumeration value="PAYER"/>
 *     <enumeration value="PAYEE"/>
 *     <enumeration value="REMITTER"/>
 *     <enumeration value="BENEFICIARY"/>
 *     <enumeration value="DISPUTEHIST"/>
 *     <enumeration value="BANK-UIDAI"/>
 *     <enumeration value="BANK"/>
 *     <enumeration value="UIDAI"/>
 *     <enumeration value="PANAADHAAR"/>
 *     <enumeration value="ADVICE"/>
 *     <enumeration value="ID"/>
 *     <enumeration value="VPA"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "txnSubType")
@XmlEnum
public enum TxnSubType {

    PAY("PAY"),
    COLLECT("COLLECT"),
    DEBIT("DEBIT"),
    CREDIT("CREDIT"),
    REFUND("REFUND"),
    REVERSAL("REVERSAL"),
    MANDATE("MANDATE"),
    CREATE("CREATE"),
    UPDATE("UPDATE"),
    REVOKE("REVOKE"),
    PAUSE("PAUSE"),
    UNPAUSE("UNPAUSE"),
    TXN("TXN"),
    DISPUTE("DISPUTE"),
    TXNDISPUTE("TXNDISPUTE"),
    PAYER("PAYER"),
    PAYEE("PAYEE"),
    REMITTER("REMITTER"),
    BENEFICIARY("BENEFICIARY"),
    DISPUTEHIST("DISPUTEHIST"),
    @XmlEnumValue("BANK-UIDAI")
    BANK_UIDAI("BANK-UIDAI"),
    BANK("BANK"),
    UIDAI("UIDAI"),
    PANAADHAAR("PANAADHAAR"),
    ADVICE("ADVICE"),
    ID("ID"),
    VPA("VPA");
    private final String value;

    TxnSubType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TxnSubType fromValue(String v) {
        for (TxnSubType c: TxnSubType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
