//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txnType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="txnType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="CWD"/>
 *     <enumeration value="CD"/>
 *     <enumeration value="RTGS"/>
 *     <enumeration value="NEFT"/>
 *     <enumeration value="UPI"/>
 *     <enumeration value="IMPS"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "txnType")
@XmlEnum
public enum TxnType {

    CWD,
    CD,
    RTGS,
    NEFT,
    UPI,
    IMPS;

    public String value() {
        return name();
    }

    public static TxnType fromValue(String v) {
        return valueOf(v);
    }

}
