//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.fss.aeps.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for uidaiData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="uidaiData">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="KycRes" type="{http://npci.org/upi/schema/}kycRes"/>
 *         <element name="TokenizeRes" type="{http://npci.org/upi/schema/}tokenizeRes"/>
 *       </sequence>
 *       <attribute name="info" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="err" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="txn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uidaiData", propOrder = {
    "kycRes",
    "tokenizeRes"
})
public class UidaiData {

    @XmlElement(name = "KycRes", required = true)
    protected KycRes kycRes;
    @XmlElement(name = "TokenizeRes", required = true)
    protected TokenizeRes tokenizeRes;
    @XmlAttribute(name = "info")
    protected String info;
    @XmlAttribute(name = "err")
    protected String err;
    @XmlAttribute(name = "txn")
    protected String txn;

    /**
     * Gets the value of the kycRes property.
     * 
     * @return
     *     possible object is
     *     {@link KycRes }
     *     
     */
    public KycRes getKycRes() {
        return kycRes;
    }

    /**
     * Sets the value of the kycRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link KycRes }
     *     
     */
    public void setKycRes(KycRes value) {
        this.kycRes = value;
    }

    /**
     * Gets the value of the tokenizeRes property.
     * 
     * @return
     *     possible object is
     *     {@link TokenizeRes }
     *     
     */
    public TokenizeRes getTokenizeRes() {
        return tokenizeRes;
    }

    /**
     * Sets the value of the tokenizeRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenizeRes }
     *     
     */
    public void setTokenizeRes(TokenizeRes value) {
        this.tokenizeRes = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfo(String value) {
        this.info = value;
    }

    /**
     * Gets the value of the err property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErr() {
        return err;
    }

    /**
     * Sets the value of the err property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErr(String value) {
        this.err = value;
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxn(String value) {
        this.txn = value;
    }

}
